# Generated by Django 4.2.4 on 2023-08-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='position',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
